#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
SOURCE_MANIFEST="$SOURCE_ROOT/SOURCE-FILES-SHA256.txt"
VARIANT="${1:-B}"
BUILD_DIR="${2:-$SOURCE_ROOT/build-perf-005-$VARIANT}"

: "${ANDROID_NDK_ROOT:?Set ANDROID_NDK_ROOT to Android NDK r27d 27.3.13750724}"
test -f "$ANDROID_NDK_ROOT/source.properties" || {
    echo 'Android NDK source.properties is missing' >&2
    exit 1
}
grep -q '^Pkg.Revision = 27\.3\.13750724$' "$ANDROID_NDK_ROOT/source.properties" || {
    echo 'PERF-005 requires Android NDK r27d 27.3.13750724' >&2
    exit 1
}
command -v cmake >/dev/null 2>&1 || { echo 'cmake is missing from PATH' >&2; exit 1; }
command -v ninja >/dev/null 2>&1 || { echo 'ninja is missing from PATH' >&2; exit 1; }
test -f "$SOURCE_MANIFEST" || { echo 'Missing SOURCE-FILES-SHA256.txt' >&2; exit 1; }
(cd "$SOURCE_ROOT" && sha256sum --quiet -c "$SOURCE_MANIFEST") || {
    echo 'Source manifest verification failed; refusing a mislabeled build' >&2
    exit 1
}

case "$VARIANT" in
    A)
        PERF005_ENABLED=OFF
        PERF_LABEL=A_CUMULATIVE_COMPARATOR
        ;;
    B)
        PERF005_ENABLED=ON
        PERF_LABEL=B_PROGRAM_AWARE_SAMPLER_BINDING
        ;;
    *)
        echo 'Usage: build-mobilegl-pz-perf-005-android.sh A|B [build-dir]' >&2
        exit 2
        ;;
esac

SOURCE_MANIFEST_SHA="$(sha256sum "$SOURCE_MANIFEST" | awk '{print $1}')"
PERF_BUILD_ID_HEX="$(printf 'PERF005-%s:%s' "$VARIANT" "$SOURCE_MANIFEST_SHA" | sha1sum | awk '{print $1}')"
[[ "$PERF_BUILD_ID_HEX" =~ ^[0-9a-f]{40}$ ]] || { echo 'Invalid Build ID' >&2; exit 1; }
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1787184000}"
export PYTHONDONTWRITEBYTECODE=1

# Canonical debug-path prefixes make independent clean builds reproducible while
# keeping A and B distinguishable only by their feature flag and Build ID.
CANONICAL_SOURCE_ROOT=/workspace/MobileGL-PZ-PERF-005-PROGRAM-AWARE-SAMPLER-BINDING-SOURCE-2026-08-24
CANONICAL_BUILD_DIR="/workspace/MobileGL-PZ-PERF-005/build/$VARIANT"
PATH_MAP_FLAGS="-ffile-prefix-map=$SOURCE_ROOT=$CANONICAL_SOURCE_ROOT -ffile-prefix-map=$BUILD_DIR=$CANONICAL_BUILD_DIR"

cmake -S "$SOURCE_ROOT" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-26 \
    -DANDROID_STL=c++_static \
    -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
    -DCMAKE_C_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_CXX_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DMOBILEGL_FORCE_RELEASE_OPT=ON \
    -DMOBILEGL_ENABLE_LTO=ON \
    -DMOBILEPZ_PERF002_PROGRAM_AWARE_TEXTURE_SYNC=ON \
    -DMOBILEPZ_PERF003_PROGRAM_AWARE_TEXTURE_BINDING=ON \
    -DMOBILEPZ_PERF005_PROGRAM_AWARE_SAMPLER_BINDING="$PERF005_ENABLED" \
    -DMOBILEPZ_PERF005_SAMPLER_TELEMETRY=ON \
    -DMOBILEGL_ENABLE_TRACY=OFF \
    -DMOBILEGL_PZCOMPAT=ON \
    -DMOBILEGL_PZCOMPAT_ABORT_TRACE=OFF \
    -DMOBILEGL_PZCOMPAT_LWJGL_THREAD_BRIDGE=ON \
    -DMOBILEPZ_V1_CANDIDATE=ON \
    -DMOBILEPZ_PZF23D2_CHUNK_FRAGDEPTH_CLAMP=OFF \
    -DMOBILEPZ_PZF23D3_CHUNK_ALPHA_TEST_PROOF=OFF \
    -DMOBILEPZ_PZF23D4_CUSTOM_ALPHA_TEST_FAMILY=ON \
    -DMOBILEPZ_V1_BUILD_ID_HEX="$PERF_BUILD_ID_HEX" \
    -DMOBILEPZ_V1_ARB_ROUTE=OFF \
    -DMOBILEPZ_CP2_TRACE=OFF \
    -DMOBILEPZ_SL1_SYNC_SHADER_LIFECYCLE=OFF \
    -DMOBILEPZ_PZF1_PZ_MATH_BUILTIN_RENAME=OFF \
    -DMOBILEPZ_V1_NG_WORLD_UNIFORM_LAYOUT_FIX=OFF \
    -DMOBILEPZ_PZF3_CROSS_FAMILY_TRACE=OFF \
    -DMOBILEPZ_PZF4_SAMPLE_SURVIVAL_TRACE=OFF \
    -DMOBILEPZ_PZF4R1_CONTEXT_LIFECYCLE_REPAIR=OFF \
    -DMOBILEPZ_PZF5_RENDER_TARGET_READBACK=OFF \
    -DMOBILEPZ_PZF6_DRAW_DELTA=OFF \
    -DMOBILEPZ_PZF7_UNIFORM_TO_NATIVE=OFF \
    -DMOBILEPZ_PZF8_OPAQUE_MODEL_BATCH_DELTA=OFF \
    -DMOBILEPZ_PZF9_MODEL_TEXTURE_UPLOAD_PROVENANCE=OFF \
    -DMOBILEPZ_PZF10_COPY_TEXTURE_REPAIR=OFF \
    -DMOBILEPZ_PZF11_MODEL_TEXTURE_GPU_READBACK=OFF \
    -DMOBILEPZ_PZF12_NULL_RT_IDENTITY_REPAIR=OFF \
    -DMOBILEPZ_PZF13_NULL_TEXTURE_PRODUCER_LINEAGE=OFF \
    -DMOBILEPZ_PZF14_CLEAR_TO_DETACH_DRAW_ROUTE=OFF \
    -DMOBILEPZ_PZF15_TEXTURE_COMBINER_SUBMISSION_TRACE=OFF \
    -DMOBILEPZ_PZF16_QUAD4_SUBMISSION_FIX=OFF \
    -DMOBILEGL_BUILD_INTEGRATION_TEST=OFF \
    -DMOBILEGL_LOG_ACTIVE_LEVEL=MOBILEGL_LOG_LEVEL_FATAL

BUILD_JOBS="${MGLPZ_BUILD_JOBS:-$(nproc)}"
if (( BUILD_JOBS > 16 )); then BUILD_JOBS=16; fi
cmake --build "$BUILD_DIR" -- -j "$BUILD_JOBS"

printf 'PERF005_VARIANT=%s\n' "$PERF_LABEL"
printf 'PERF005_LTO=ON\n'
printf 'PERF005_TELEMETRY=BOUNDED_4096\n'
printf 'PERF005_BUILD_DIR=%s\n' "$BUILD_DIR"
printf 'PERF005_SOURCE_MANIFEST_SHA256=%s\n' "$SOURCE_MANIFEST_SHA"
printf 'PERF005_SOURCE_BUILD_ID=%s\n' "$PERF_BUILD_ID_HEX"
