#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
VARIANT="${1:-FIX}"
case "${VARIANT^^}" in
    FIX)
        VARIANT='FIX'
        FORCE_VISIBLE='OFF'
        ;;
    WFX_PROBE|WFX-PROBE|PROBE)
        VARIANT='WFX_PROBE'
        FORCE_VISIBLE='ON'
        ;;
    *)
        echo 'Variant invalid: use FIX or WFX_PROBE.' >&2
        exit 2
        ;;
esac
BUILD_DIR="${2:-$SOURCE_ROOT/build-bug002-bug003-${VARIANT,,}}"

: "${ANDROID_NDK_ROOT:?Set ANDROID_NDK_ROOT to Android NDK r27d 27.3.13750724}"
test -f "$ANDROID_NDK_ROOT/source.properties"
grep -q '^Pkg.Revision = 27\.3\.13750724$' "$ANDROID_NDK_ROOT/source.properties"

SOURCE_ID="$({
    find "$SOURCE_ROOT/MobileGL" "$SOURCE_ROOT/include" "$SOURCE_ROOT/3rdparty" \
         "$SOURCE_ROOT/buildsystem" -type f -print0
    printf '%s\0' "$SOURCE_ROOT/CMakeLists.txt"
} | sort -z | xargs -0 sha256sum | sed "s#${SOURCE_ROOT}/##" | sha256sum | awk '{print $1}')"
BUILD_ID="$(printf 'BUG002-BUG003:%s:%s' "$VARIANT" "$SOURCE_ID" | sha1sum | awk '{print $1}')"

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1787529600}"
export PYTHONDONTWRITEBYTECODE=1

CANONICAL_SOURCE_ROOT=/workspace/MobileGL-PZ-BUG002-BUG003
CANONICAL_BUILD_DIR="/workspace/MobileGL-PZ-BUG002-BUG003/build-${VARIANT,,}"
PATH_MAP_FLAGS="-ffile-prefix-map=$SOURCE_ROOT=$CANONICAL_SOURCE_ROOT -ffile-prefix-map=$BUILD_DIR=$CANONICAL_BUILD_DIR"

cmake -S "$SOURCE_ROOT" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-26 \
    -DANDROID_STL=c++_static \
    -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
    -DCMAKE_C_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_CXX_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DMOBILEGL_FORCE_RELEASE_OPT=ON \
    -DMOBILEGL_ENABLE_LTO=OFF \
    -DMOBILEPZ_OPT_LAB=ON \
    -DMOBILEPZ_OPT_LAB_BUILD_VARIANT="BUG002-BUG003-${VARIANT}" \
    -DMOBILEPZ_OPT_LAB_BUILD_ID="$BUILD_ID" \
    -DMOBILEPZ_PERF002_PROGRAM_AWARE_TEXTURE_SYNC=ON \
    -DMOBILEPZ_PERF003_PROGRAM_AWARE_TEXTURE_BINDING=ON \
    -DMOBILEPZ_PERF005_PROGRAM_AWARE_SAMPLER_BINDING=ON \
    -DMOBILEPZ_PERF005_SAMPLER_TELEMETRY=OFF \
    -DMOBILEGL_ENABLE_TRACY=OFF \
    -DMOBILEGL_PZCOMPAT=ON \
    -DMOBILEGL_PZCOMPAT_ABORT_TRACE=OFF \
    -DMOBILEGL_PZCOMPAT_LWJGL_THREAD_BRIDGE=ON \
    -DMOBILEPZ_V1_CANDIDATE=ON \
    -DMOBILEPZ_PZF23D2_CHUNK_FRAGDEPTH_CLAMP=OFF \
    -DMOBILEPZ_PZF23D3_CHUNK_ALPHA_TEST_PROOF=OFF \
    -DMOBILEPZ_PZF23D4_CUSTOM_ALPHA_TEST_FAMILY=ON \
    -DMOBILEPZ_V1_BUILD_ID_HEX="$BUILD_ID" \
    -DMOBILEPZ_PZF16_QUAD4_SUBMISSION_FIX=OFF \
    -DMOBILEPZ_BUG002_WFX_BLEND_FIX=ON \
    -DMOBILEPZ_BUG002_WFX_FORCE_VISIBLE="$FORCE_VISIBLE" \
    -DMOBILEPZ_BUG003_HORSE_BOUNDED_QUADS=ON \
    -DMOBILEGL_BUILD_INTEGRATION_TEST=OFF \
    -DMOBILEGL_LOG_ACTIVE_LEVEL=MOBILEGL_LOG_LEVEL_WARN

BUILD_JOBS="${MGLPZ_BUILD_JOBS:-$(nproc)}"
if (( BUILD_JOBS > 16 )); then BUILD_JOBS=16; fi
cmake --build "$BUILD_DIR" -- -j "$BUILD_JOBS"

test -f "$BUILD_DIR/libMobileGLPZ.so"
printf 'BUILD_DIR=%s\n' "$BUILD_DIR"
printf 'BUILD_ID=%s\n' "$BUILD_ID"
printf 'SOURCE_ID=%s\n' "$SOURCE_ID"
printf 'VARIANT=%s\n' "$VARIANT"
printf 'WFX_FORCE_VISIBLE=%s\n' "$FORCE_VISIBLE"
