#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
VARIANT="${1:-THINLTO}"
case "${VARIANT^^}" in
    THINLTO|LTO) VARIANT='THINLTO'; LTO='ON' ;;
    NOLTO|NO-LTO) VARIANT='NOLTO'; LTO='OFF' ;;
    *) echo 'Variantă invalidă. Folosește THINLTO sau NOLTO.' >&2; exit 2 ;;
esac
BUILD_DIR="${2:-$SOURCE_ROOT/build-opt-lab-v3-022-${VARIANT,,}}"

: "${ANDROID_NDK_ROOT:?Set ANDROID_NDK_ROOT to Android NDK r27d 27.3.13750724}"
test -f "$ANDROID_NDK_ROOT/source.properties"
grep -q '^Pkg.Revision = 27\.3\.13750724$' "$ANDROID_NDK_ROOT/source.properties"

# Build-relevant tree identity. Paths and file hashes are sorted and independent
# of mtimes, archive layout and the local checkout path.
SOURCE_ID="$({
    find "$SOURCE_ROOT/MobileGL" "$SOURCE_ROOT/include" "$SOURCE_ROOT/3rdparty" \
         "$SOURCE_ROOT/buildsystem" -type f -print0
    printf '%s\0' "$SOURCE_ROOT/CMakeLists.txt"
} | sort -z | xargs -0 sha256sum | sed "s#${SOURCE_ROOT}/##" | sha256sum | awk '{print $1}')"
BUILD_ID="$(printf 'OPT-LAB-V3-022:%s:%s' "$VARIANT" "$SOURCE_ID" | sha1sum | awk '{print $1}')"

export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1787529600}"
export PYTHONDONTWRITEBYTECODE=1

CANONICAL_SOURCE_ROOT=/workspace/MobileGL-PZ-OPT-LAB-V3-022
CANONICAL_BUILD_DIR="/workspace/MobileGL-PZ-OPT-LAB-V3-022/build-${VARIANT,,}"
PATH_MAP_FLAGS="-ffile-prefix-map=$SOURCE_ROOT=$CANONICAL_SOURCE_ROOT -ffile-prefix-map=$BUILD_DIR=$CANONICAL_BUILD_DIR"

cmake -S "$SOURCE_ROOT" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-26 \
    -DANDROID_STL=c++_static \
    -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
    -DCMAKE_C_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_CXX_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DMOBILEGL_FORCE_RELEASE_OPT=ON \
    -DMOBILEGL_ENABLE_LTO="$LTO" \
    -DMOBILEPZ_OPT_LAB=ON \
    -DMOBILEPZ_OPT_LAB_BUILD_VARIANT="$VARIANT" \
    -DMOBILEPZ_OPT_LAB_BUILD_ID="$BUILD_ID" \
    -DMOBILEPZ_PERF002_PROGRAM_AWARE_TEXTURE_SYNC=ON \
    -DMOBILEPZ_PERF003_PROGRAM_AWARE_TEXTURE_BINDING=ON \
    -DMOBILEPZ_PERF005_PROGRAM_AWARE_SAMPLER_BINDING=ON \
    -DMOBILEPZ_PERF005_SAMPLER_TELEMETRY=OFF \
    -DMOBILEGL_ENABLE_TRACY=OFF \
    -DMOBILEGL_PZCOMPAT=ON \
    -DMOBILEGL_PZCOMPAT_ABORT_TRACE=OFF \
    -DMOBILEGL_PZCOMPAT_LWJGL_THREAD_BRIDGE=ON \
    -DMOBILEPZ_V1_CANDIDATE=ON \
    -DMOBILEPZ_PZF23D2_CHUNK_FRAGDEPTH_CLAMP=OFF \
    -DMOBILEPZ_PZF23D3_CHUNK_ALPHA_TEST_PROOF=OFF \
    -DMOBILEPZ_PZF23D4_CUSTOM_ALPHA_TEST_FAMILY=ON \
    -DMOBILEPZ_V1_BUILD_ID_HEX="$BUILD_ID" \
    -DMOBILEPZ_V1_ARB_ROUTE=OFF \
    -DMOBILEPZ_CP2_TRACE=OFF \
    -DMOBILEPZ_SL1_SYNC_SHADER_LIFECYCLE=OFF \
    -DMOBILEPZ_PZF1_PZ_MATH_BUILTIN_RENAME=OFF \
    -DMOBILEPZ_V1_NG_WORLD_UNIFORM_LAYOUT_FIX=OFF \
    -DMOBILEPZ_PZF3_CROSS_FAMILY_TRACE=OFF \
    -DMOBILEPZ_PZF4_SAMPLE_SURVIVAL_TRACE=OFF \
    -DMOBILEPZ_PZF4R1_CONTEXT_LIFECYCLE_REPAIR=OFF \
    -DMOBILEPZ_PZF5_RENDER_TARGET_READBACK=OFF \
    -DMOBILEPZ_PZF6_DRAW_DELTA=OFF \
    -DMOBILEPZ_PZF7_UNIFORM_TO_NATIVE=OFF \
    -DMOBILEPZ_PZF8_OPAQUE_MODEL_BATCH_DELTA=OFF \
    -DMOBILEPZ_PZF9_MODEL_TEXTURE_UPLOAD_PROVENANCE=OFF \
    -DMOBILEPZ_PZF10_COPY_TEXTURE_REPAIR=OFF \
    -DMOBILEPZ_PZF11_MODEL_TEXTURE_GPU_READBACK=OFF \
    -DMOBILEPZ_PZF12_NULL_RT_IDENTITY_REPAIR=OFF \
    -DMOBILEPZ_PZF13_NULL_TEXTURE_PRODUCER_LINEAGE=OFF \
    -DMOBILEPZ_PZF14_CLEAR_TO_DETACH_DRAW_ROUTE=OFF \
    -DMOBILEPZ_PZF15_TEXTURE_COMBINER_SUBMISSION_TRACE=OFF \
    -DMOBILEPZ_PZF16_QUAD4_SUBMISSION_FIX=OFF \
    -DMOBILEGL_BUILD_INTEGRATION_TEST=OFF \
    -DMOBILEGL_LOG_ACTIVE_LEVEL=MOBILEGL_LOG_LEVEL_FATAL

BUILD_JOBS="${MGLPZ_BUILD_JOBS:-$(nproc)}"
if (( BUILD_JOBS > 16 )); then BUILD_JOBS=16; fi
cmake --build "$BUILD_DIR" -- -j "$BUILD_JOBS"

printf 'OPT_LAB_BUILD_DIR=%s\n' "$BUILD_DIR"
printf 'OPT_LAB_BUILD_ID=%s\n' "$BUILD_ID"
printf 'OPT_LAB_SOURCE_ID=%s\n' "$SOURCE_ID"
printf 'OPT_LAB_VARIANT=%s\n' "$VARIANT"
printf 'OPT_LAB_THINLTO=%s\n' "$LTO"
printf 'OPT_LAB_SUPPORTED=002,003,004R,005,006,007,008,009,010,011,012,013,014,015,016,017,018,019,020,021A,021B,021C,021D,021E,022A,022B,022C,022D,022E\n'
