#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
SOURCE_MANIFEST="$SOURCE_ROOT/SOURCE-FILES-SHA256.txt"
VARIANT="${1:-D}"
BUILD_DIR="${2:-$SOURCE_ROOT/build-perf-003-$VARIANT}"

: "${ANDROID_NDK_ROOT:?Set ANDROID_NDK_ROOT to Android NDK r27d 27.3.13750724}"
test -f "$SOURCE_MANIFEST" || { echo 'Missing SOURCE-FILES-SHA256.txt' >&2; exit 1; }
(cd "$SOURCE_ROOT" && sha256sum --quiet -c "$SOURCE_MANIFEST") || {
    echo 'Source manifest verification failed; refusing a mislabeled build' >&2
    exit 1
}

case "$VARIANT" in
    C)
        PERF003_ENABLED=OFF
        PERF_BUILD_ID_HEX=0d0c68328824ae9b279efefc8a49f3dcc96d4492
        PERF_LABEL=C_PERF002_COMPARATOR
        ;;
    D)
        PERF003_ENABLED=ON
        PERF_BUILD_ID_HEX="$(sha1sum "$SOURCE_MANIFEST" | awk '{print $1}')"
        PERF_LABEL=D_PROGRAM_TEXTURE_BINDING
        ;;
    *)
        echo 'Usage: build-mobilegl-pz-perf-003-android.sh C|D [build-dir]' >&2
        exit 2
        ;;
esac

[[ "$PERF_BUILD_ID_HEX" =~ ^[0-9a-f]{40}$ ]] || { echo 'Invalid Build ID' >&2; exit 1; }
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1787184000}"
export PYTHONDONTWRITEBYTECODE=1

# The published PERF-002 binary was built from these canonical path prefixes.
# Clang expands __FILE__ in validation/log strings even at FATAL log level, so a
# copied source tree would otherwise differ massively despite identical disabled
# code. Map both source and generated-file prefixes back to PERF-002. This makes
# variant C a meaningful byte-for-byte isolation gate; it does not change paths
# opened at runtime.
CANONICAL_SOURCE_ROOT=/workspace/scratch/c16390112933/work/MobileGL-PZ-PERF-002-PROGRAM-AWARE-TEXTURE-SYNC-SOURCE-2026-08-24
CANONICAL_BUILD_DIR=/workspace/scratch/c16390112933/work/PERF-002-PROGRAM-AWARE-TEXTURE-SYNC/build/C_PROGRAM_TEXTURE_SYNC
PATH_MAP_FLAGS="-ffile-prefix-map=$SOURCE_ROOT=$CANONICAL_SOURCE_ROOT -ffile-prefix-map=$BUILD_DIR=$CANONICAL_BUILD_DIR"

cmake -S "$SOURCE_ROOT" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-26 \
    -DANDROID_STL=c++_static \
    -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
    -DCMAKE_C_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_CXX_FLAGS="$PATH_MAP_FLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DMOBILEGL_FORCE_RELEASE_OPT=ON \
    -DMOBILEGL_ENABLE_LTO=OFF \
    -DMOBILEPZ_PERF002_PROGRAM_AWARE_TEXTURE_SYNC=ON \
    -DMOBILEPZ_PERF003_PROGRAM_AWARE_TEXTURE_BINDING="$PERF003_ENABLED" \
    -DMOBILEGL_ENABLE_TRACY=OFF \
    -DMOBILEGL_PZCOMPAT=ON \
    -DMOBILEGL_PZCOMPAT_ABORT_TRACE=OFF \
    -DMOBILEGL_PZCOMPAT_LWJGL_THREAD_BRIDGE=ON \
    -DMOBILEPZ_V1_CANDIDATE=ON \
    -DMOBILEPZ_PZF23D2_CHUNK_FRAGDEPTH_CLAMP=OFF \
    -DMOBILEPZ_PZF23D3_CHUNK_ALPHA_TEST_PROOF=OFF \
    -DMOBILEPZ_PZF23D4_CUSTOM_ALPHA_TEST_FAMILY=ON \
    -DMOBILEPZ_V1_BUILD_ID_HEX="$PERF_BUILD_ID_HEX" \
    -DMOBILEPZ_V1_ARB_ROUTE=OFF \
    -DMOBILEPZ_CP2_TRACE=OFF \
    -DMOBILEPZ_SL1_SYNC_SHADER_LIFECYCLE=OFF \
    -DMOBILEPZ_PZF1_PZ_MATH_BUILTIN_RENAME=OFF \
    -DMOBILEPZ_V1_NG_WORLD_UNIFORM_LAYOUT_FIX=OFF \
    -DMOBILEPZ_PZF3_CROSS_FAMILY_TRACE=OFF \
    -DMOBILEPZ_PZF4_SAMPLE_SURVIVAL_TRACE=OFF \
    -DMOBILEPZ_PZF4R1_CONTEXT_LIFECYCLE_REPAIR=OFF \
    -DMOBILEPZ_PZF5_RENDER_TARGET_READBACK=OFF \
    -DMOBILEPZ_PZF6_DRAW_DELTA=OFF \
    -DMOBILEPZ_PZF7_UNIFORM_TO_NATIVE=OFF \
    -DMOBILEPZ_PZF8_OPAQUE_MODEL_BATCH_DELTA=OFF \
    -DMOBILEPZ_PZF9_MODEL_TEXTURE_UPLOAD_PROVENANCE=OFF \
    -DMOBILEPZ_PZF10_COPY_TEXTURE_REPAIR=OFF \
    -DMOBILEPZ_PZF11_MODEL_TEXTURE_GPU_READBACK=OFF \
    -DMOBILEPZ_PZF12_NULL_RT_IDENTITY_REPAIR=OFF \
    -DMOBILEPZ_PZF13_NULL_TEXTURE_PRODUCER_LINEAGE=OFF \
    -DMOBILEPZ_PZF14_CLEAR_TO_DETACH_DRAW_ROUTE=OFF \
    -DMOBILEPZ_PZF15_TEXTURE_COMBINER_SUBMISSION_TRACE=OFF \
    -DMOBILEPZ_PZF16_QUAD4_SUBMISSION_FIX=OFF \
    -DMOBILEGL_BUILD_INTEGRATION_TEST=OFF \
    -DMOBILEGL_LOG_ACTIVE_LEVEL=MOBILEGL_LOG_LEVEL_FATAL

cmake --build "$BUILD_DIR" -- -j "$(nproc)"

printf 'PERF003_VARIANT=%s\n' "$PERF_LABEL"
printf 'PERF003_LTO=OFF\n'
printf 'PERF003_BUILD_DIR=%s\n' "$BUILD_DIR"
printf 'PERF003_SOURCE_BUILD_ID=%s\n' "$PERF_BUILD_ID_HEX"
